# Generated by Django 5.2 on 2025-04-09 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LFSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pw_hash', models.CharField(max_length=256)),
                ('user_lastlogintime', models.DateTimeField(verbose_name='last login')),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon_path', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LFSTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('did_buyback', models.BooleanField()),
                ('lfs_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastfanstanding.lfsuser')),
            ],
        ),
        migrations.CreateModel(
            name='LFSPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfl_week', models.IntegerField()),
                ('win_loss', models.BooleanField()),
                ('lfs_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastfanstanding.lfsteam')),
                ('nfl_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastfanstanding.nflteam')),
            ],
        ),
    ]
