# Generated by Django 5.2 on 2025-04-09 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfanstanding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='bye_week',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
