# Generated by Django 5.2 on 2025-04-10 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfanstanding', '0002_nflteam_bye_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='LFSGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('pot_size', models.IntegerField(default=0)),
                ('total_teams', models.IntegerField(default=0)),
                ('current_week', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='lfspick',
            name='nfl_week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='lfsteam',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lfsteam',
            name='did_buyback',
            field=models.BooleanField(default=False),
        ),
    ]
