# Generated by Django 5.2 on 2025-04-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastfanstanding', '0003_lfsgame_alter_lfspick_nfl_week_alter_lfsteam_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lfsuser',
            old_name='user_lastlogintime',
            new_name='last_login',
        ),
        migrations.RemoveField(
            model_name='lfsuser',
            name='user_pw_hash',
        ),
    ]
