# Generated by Django 5.2 on 2025-04-10 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastfanstanding', '0004_rename_user_lastlogintime_lfsuser_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfsteam',
            name='lfs_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lastfanstanding.lfsgame'),
            preserve_default=False,
        ),
    ]
